### ISSUE TITLE
RadioThermostat time

### ISSUE THREAD

**Issue by hugo-lyppens** [ceesb/radiothermostat_cloud#1]
Can this replacement of the radio thermostat provide time to the thermostat? I have 3 radio thermostats and they often have incorrect clock time. How to set the NTP server and time zone of the thermostat? How often does the thermostat refresh its time? Does it get time via NTP or via the cloud service URL?

**Comment by ceesb** [comment]
It is probably set by the server backend, but I do not know this for a fact. My thermostat is in a box somewhere, so I can't try. I just added a file [servercommands.txt](https://github.com/ceesb/radiothermostat_cloud/blob/master/servercommands.txt) to the repo with messages that the server can respond to the thermostat: one in there is "time", which presumably sets the time on the thermostat. It may be that you can call a similar command through the thermostat's own LAN interface, but again, I can't try, and I don't know for sure.
